Ci 71
creativiso/invoice pull request #57
Opened 2024-02-06 13:50 UTC by eneschelebi03

Proform and invoice forms autofilled when editing

2024-02-06 14:47 UTC, a-katsarov requested changes

2024-02-06 14:47 UTC, a-katsarov commented on apps/frontend/src/app/modules/contractors/contractor/contractor.component.ts
> +    console.log('Form data:', contractorData); // log the form data
Махни го този console.log

2024-02-06 14:47 UTC, a-katsarov commented on apps/frontend/src/app/modules/invoices/invoice/invoice.component.ts
> +      p_name: '',
Тези защо остават празни, ако не се използват?

2024-02-06 15:25 UTC, eneschelebi03 commented on apps/frontend/src/app/modules/contractors/contractor/contractor.component.ts
> +    console.log('Form data:', contractorData); // log the form data
готово

2024-02-06 15:25 UTC, eneschelebi03 commented on apps/frontend/src/app/modules/invoices/invoice/invoice.component.ts
> +      p_name: '',
премахнати са

2024-02-06 15:26 UTC, eneschelebi03 commented on apps/frontend/src/app/modules/invoices/invoice/invoice.component.ts
> +      p_name: '',
вече работи и без тях. създават се успешно проформи и фактури

2024-02-12 15:25 UTC, a-katsarov approved these changes

2024-02-12 15:25 UTC, merged